### ISSUE TITLE
update to 0.6.1 failed on OSX yosemite

### ISSUE THREAD

**Issue by dotnetCarpenter** [lloeki/svg-preview#18]
Seems I'm missing a library but I'm not sure which one or how to get it. `ld: library not found for -lgcc_s.10.5`

Error message:
```
> runas@2.0.0 install /private/var/folders/br/bhnw4sc955vgj97xpwz_2_ww0000gn/T/apm-install-dir-115106-5739-1uh5wc5/node_modules/svg-preview/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/private/var/folders/br/bhnw4sc955vgj97xpwz_2_ww0000gn/T/apm-install-dir-115106-5739-1uh5wc5/node_modules/svg-preview/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node
runas.target.mk:152: recipe for target 'Release/runas.node' failed
make: Leaving directory '/private/var/folders/br/bhnw4sc955vgj97xpwz_2_ww0000gn/T/apm-install-dir-115106-5739-1uh5wc5/node_modules/svg-preview/node_modules/pathwatcher/node_modules/runas/build'

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/runas.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/br/bhnw4sc955vgj97xpwz_2_ww0000gn/T/apm-install-dir-115106-5739-1uh5wc5/node_modules/svg-preview/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Volumes/mystuff/dotnetCarpenter/.atom/.apm/.apmrc" "--userconfig" "/Volumes/mystuff/dotnetCarpenter/.atom/.apmrc" "install" "/private/var/folders/br/bhnw4sc955vgj97xpwz_2_ww0000gn/T/d-115106-5739-34le87/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/br/bhnw4sc955vgj97xpwz_2_ww0000gn/T/apm-install-dir-115106-5739-1uh5wc5/npm-debug.log
```

**Comment by dotnetCarpenter** [comment]
~~Strike~~ that. I had upgraded xcode cli but not xcode itself.

**Comment by lloeki** [comment]
No worries, happens to me all the time. `xcode-select --install` seems to do yet some other thing that may help too.
